sudo: required
services:
    - docker
    
before_install:
    docker build -t pkumarbp/docker-react -f Dockerfile.dev .
    
script:
    docker run pkumarbp/docker-react npm run test -- --coverage
    